IF  OBJECT_ID('ASIGNATURAS')IS NOT NULL
DROP TABLE ASIGNATURAS
GO
CREATE TABLE ASIGNATURAS(
ID INT IDENTITY(1,1),
CODIGO VARCHAR(10) NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(40) UNIQUE NOT NULL,
CREDITOS INT NOT NULL
)

IF  OBJECT_ID('ESTUDIANTES')IS NOT NULL
DROP TABLE ESTUDIANTES 
GO
CREATE TABLE ESTUDIANTES(
ID INT IDENTITY(1,1),
CODIGO VARCHAR(10) NOT NULL PRIMARY KEY,
NOMBRES VARCHAR(40) NOT NULL,
APELLIDOS VARCHAR(40) NOT NULL,
SEMESTRE INT NOT NULL,
CARRERA VARCHAR(40) NOT NULL,
COD_ASIG VARCHAR(10) NOT NULL
CONSTRAINT FK_ESTUDIANTE_ASIGNATURA 
FOREIGN KEY REFERENCES ASIGNATURAS(CODIGO)
ON UPDATE CASCADE
ON DELETE CASCADE
)

IF  OBJECT_ID('DOCENTES')IS NOT NULL
DROP TABLE DOCENTES
GO
CREATE TABLE DOCENTES(
ID INT IDENTITY(1,1) NOT NULL,
CODIGO VARCHAR(10) NOT NULL PRIMARY KEY,
NOMBRES VARCHAR(30) NOT NULL,
APELLIDOS VARCHAR(30) NOT NULL,
COD_ASIG VARCHAR(10) NOT NULL
CONSTRAINT FK_DOCENTE_ASIGNATURA FOREIGN KEY
REFERENCES ASIGNATURAS(CODIGO)
ON UPDATE CASCADE
ON DELETE CASCADE
)

IF  OBJECT_ID('RECORD')IS NOT NULL
DROP TABLE RECORD
GO
CREATE TABLE RECORD(
ID INT IDENTITY(1,1) NOT NULL,
CODIGO VARCHAR(10) NOT NULL PRIMARY KEY,
FECHA_CREACION DATE DEFAULT GETDATE(),
PERIODO VARCHAR(10) NOT NULL,
NOTA1 DECIMAL(2,1)NOT NULL CHECK(NOTA1<5.1),
NOTA2 DECIMAL(2,1)NOT NULL CHECK(NOTA2<5.1),
PROMEDIO AS (NOTA1+NOTA2)/2,
ESTUDIANTE_COD VARCHAR(10) NOT NULL
CONSTRAINT FK_RECORD_ESTUDIANTE FOREIGN KEY
REFERENCES ESTUDIANTES(CODIGO)
ON UPDATE NO ACTION
ON DELETE NO ACTION,
DOCENTE_COD VARCHAR(10) NOT NULL
CONSTRAINT FK_RECORD_DOCENTE FOREIGN KEY
REFERENCES DOCENTES(CODIGO)
ON UPDATE NO ACTION
ON DELETE NO ACTION
)


--::::::::::::::::::::::::::::::::::::SP_ASIGNATURA::::::::::::::::::::::::::::::
CREATE PROC SP_I_ASIGNATURA
(
@CODIGO VARCHAR(10),
@NOMBRE VARCHAR(40),
@CREDITOS INT 
)
AS
    BEGIN
    INSERT INTO [dbo].[ASIGNATURAS]
           ([CODIGO]
           ,[NOMBRE]
           ,[CREDITOS])
     VALUES
           (@CODIGO, @NOMBRE, @CREDITOS)
    END
--*******
CREATE PROC SP_S_ASIGNATURAS
AS 
  BEGIN
  SELECT * FROM ASIGNATURAS
  END
--******
CREATE PROC SP_SXID_ASIGNATURAS
  (@ID INT)
AS 
  BEGIN 
  SELECT * FROM ASIGNATURAS WHERE ID=@ID
  END 
--*********
CREATE PROC SP_D_ASIGNATURAS
(@ID INT)
AS 
  BEGIN 
  DELETE FROM ASIGNATURAS WHERE ID=@ID
  END 
--**********
CREATE PROC SP_U_ASIGNATURAS
  (
  @ID INT,
  @CODIGO VARCHAR(10),
  @NOMBRE VARCHAR(40),
  @CREDITOS INT 
  )
AS 
  BEGIN 
  UPDATE ASIGNATURAS SET CODIGO=@CODIGO, NOMBRE=@NOMBRE, CREDITOS=@CREDITOS WHERE ID=@ID
  END

--::::::::::::::::::::::::::::::::::::END SP_ASIGNATURA::::::::::::::::::::::::::::::
    
--::::::::::::::::::::::::::::::::::::SP_ESTUDIANTES::::::::::::::::::::::::::::::
  
CREATE PROC SP_I_ESTUDIANTES
(
@CODIGO VARCHAR(10),
@NOMBRES VARCHAR(40),
@APELLIDOS VARCHAR(40),
@SEMESTRE INT,
@CARRERA VARCHAR(40),
@COD_ASIG VARCHAR(10)
)
AS
    BEGIN
    INSERT INTO [dbo].[ESTUDIANTES]
           ([CODIGO]
           ,[NOMBRES]
           ,[APELLIDOS]
           ,[SEMESTRE]
           ,[CARRERA]
           ,[COD_ASIG])
     VALUES
           (@CODIGO, @NOMBRES, @APELLIDOS, @SEMESTRE, @CARRERA, @COD_ASIG)
    END

CREATE PROC SP_S_ESTUDIANTES
AS 
  BEGIN
  SELECT * FROM ESTUDIANTES
  END
--********
CREATE PROC SP_SXID_ESTUDIANTES
  (@ID INT)
AS 
  BEGIN 
  SELECT * FROM ESTUDIANTES WHERE ID=@ID
  END
--*********
CREATE PROC SP_D_ESTUDIANTES
(@ID INT)
AS 
  BEGIN 
  DELETE FROM ESTUDIANTES WHERE ID=@ID
  END 
--**********
CREATE PROC SP_U_ESTUDIANTES
  (
  @ID INT,
  @CODIGO VARCHAR(10),
  @NOMBRES VARCHAR(40),
  @APELLIDOS VARCHAR(40),
  @SEMESTRE INT,
  @CARRERA VARCHAR(40),
  @COD_ASIG VARCHAR(10) 
  )
AS 
  BEGIN 
  UPDATE ESTUDIANTES SET CODIGO=@CODIGO, NOMBRES=@NOMBRES, APELLIDOS=@APELLIDOS, SEMESTRE=@SEMESTRE, CARRERA=@CARRERA, COD_ASIG=@COD_ASIG  WHERE ID=@ID
  END

   
--::::::::::::::::::::::::::::::::::::END SP_ESTUDIANTES::::::::::::::::::::::::::::::

--::::::::::::::::::::::::::::::::::::END SP__DOCENTES::::::::::::::::::::::::::::::
    
CREATE PROC SP_I_DOCENTES
(
@CODIGO VARCHAR(10),
@NOMBRES VARCHAR(30),
@APELLIDOS VARCHAR(30),
@COD_ASIG VARCHAR(10) 
)
AS
    BEGIN
    INSERT INTO [dbo].[DOCENTES]
           ([CODIGO]
           ,[NOMBRES]
           ,[APELLIDOS]
           ,[COD_ASIG])
     VALUES
           (@CODIGO, @NOMBRES, @APELLIDOS, @COD_ASIG)
    END

CREATE PROC SP_S_DOCENTES
AS 
  BEGIN
  SELECT * FROM DOCENTES
  END
--********
CREATE PROC SP_SXID_DOCENTES
  (@ID INT)
AS 
  BEGIN 
  SELECT * FROM DOCENTES WHERE ID=@ID
  END
--*********
CREATE PROC SP_D_DOCENTES
(@ID INT)
AS 
  BEGIN 
  DELETE FROM DOCENTES WHERE ID=@ID
  END 
--**********
CREATE PROC SP_U_DOCENTES
  (
  @ID INT,
  @CODIGO VARCHAR(10),
  @NOMBRES VARCHAR(30),
  @APELLIDOS VARCHAR(30),
  @COD_ASIG VARCHAR(10) 
  )
AS 
  BEGIN 
  UPDATE DOCENTES SET CODIGO=@CODIGO, NOMBRES=@NOMBRES, APELLIDOS=@APELLIDOS, COD_ASIG=@COD_ASIG  WHERE ID=@ID
  END
  
--::::::::::::::::::::::::::::::::::::END SP__DOCENTES::::::::::::::::::::::::::::::


--::::::::::::::::::::::::::::::::::::END SP__RECORD::::::::::::::::::::::::::::::
CREATE PROC SP_I_RECORD
(
@CODIGO VARCHAR(10), 
@PERIODO VARCHAR(10),
@NOTA1 DECIMAL(2,1),
@NOTA2 DECIMAL(2,1),
@ESTUDIANTE_COD VARCHAR(10),
@DOCENTE_COD VARCHAR(10)
)
AS
    BEGIN
    INSERT INTO [dbo].[RECORD]
           ([CODIGO]
           ,[PERIODO]
           ,[NOTA1]
           ,[NOTA2]
           ,[ESTUDIANTE_COD]
           ,[DOCENTE_COD])
     VALUES
           (@CODIGO, @PERIODO, @NOTA1, @NOTA2, @ESTUDIANTE_COD, @DOCENTE_COD)
    END    

CREATE PROC SP_S_RECORD
AS 
  BEGIN
  SELECT * FROM RECORD
  END
--********
CREATE PROC SP_SXID_RECORD
  (@ID INT)
AS 
  BEGIN 
  SELECT * FROM RECORD WHERE ID=@ID
  END
--*********
CREATE PROC SP_D_RECORD
(@ID INT)
AS 
  BEGIN 
  DELETE FROM RECORD WHERE ID=@ID
  END 
--**********
CREATE PROC SP_U_RECORD
  (
  @ID INT,
  @CODIGO VARCHAR(10), 
  @FECHA_CREACION DATE,
  @PERIODO VARCHAR(10),
  @NOTA1 DECIMAL(2,1),
  @NOTA2 DECIMAL(2,1),
  @ESTUDIANTE_COD VARCHAR(10),
  @DOCENTE_COD VARCHAR(10) 
  )
AS 
  BEGIN 
  UPDATE RECORD SET CODIGO=@CODIGO, FECHA_CREACION=@FECHA_CREACION, PERIODO=@PERIODO, NOTA1=@NOTA1, NOTA2=@NOTA2, ESTUDIANTE_COD=@ESTUDIANTE_COD, DOCENTE_COD=@DOCENTE_COD   WHERE ID=@ID
  END
--::::::::::::::::::::::::::::::::::::END SP__RECORD::::::::::::::::::::::::::::::





CREATE PROC SP_REPORTE
AS 
  BEGIN
    SELECT 
    RE.CODIGO , RE.FECHA_CREACION, RE.PERIODO,
    CONCAT(ES.NOMBRES,' ',ES.APELLIDOS) AS [ESTUDIANTE],
    RE.NOTA1, RE.NOTA2, RE.PROMEDIO, 
    CONCAT(DO.NOMBRES,' ',DO.APELLIDOS) AS [DOCENTE],
    ASIG.NOMBRE AS [ASIGNATURA], ASIG.CREDITOS
    --
    FROM RECORD AS RE
    INNER JOIN ESTUDIANTES AS ES
    ON RE.ESTUDIANTE_COD = ES.CODIGO
    INNER JOIN DOCENTES AS DO
    ON RE.DOCENTE_COD = DO.CODIGO
    INNER JOIN ASIGNATURAS AS ASIG
    ON ASIG.CODIGO = DO.COD_ASIG
  END





